### ISSUE TITLE
Validation error on checks with decimal values in v0.0.10

### ISSUE THREAD

**Issue by brittenhouse** [grafana/synthetic-monitoring-app#102]
In v0.0.10 we switched UI elements to use sliders+input fields for checks. If a user types a decimal value in the input we don't show an error on tab out, but do show an error when saving the check.  Possibly might want to allow saving decimals or not allow them to be entered.

![timeout](https://user-images.githubusercontent.com/1685639/93612544-9ef10a00-f99d-11ea-9285-758a062f39ad.png)

**Comment by rdubrock** [comment]
Good catch, looks like this is due to the slider requiring an integer. I have a fix into `@grafana/ui` that will go out with `7.2`.
