### ISSUE TITLE
Update error message when multiple instances are detected

### ISSUE THREAD

**Issue by brittenhouse** [grafana/synthetic-monitoring-app#145]
When multiple instances of the synthetic monitoring plugin are installed (e.g. by adding them to the plugin directory with multiple names?), the code hits:

The current message is: 
https://github.com/grafana/synthetic-monitoring-app/blob/b84ce0f87f980bd8c925cd8033f7225a00a000eb/src/RootPage.tsx#L208

The error message should be updated with an explanation for what to do. Ideally the error message can point to the directories containing each instance.

Could this refer to multiple instances of the SM datasource?

**Comment by electron0zero** [comment]
This part of code, seems to deleted now, and I think with provisoning this is no longer an issue.
