### ISSUE TITLE
General usage improvements

### ISSUE THREAD

**Issue by nathanrodman** [grafana/synthetic-monitoring-app#162]
Some options:

- Show usage per check
- Total roll up usage for all checks
- Total costs per check
- Total costs for Synthetic Monitoring
- Tooltip explaining parameters that affect usage
- Explore making calculated usage outside of form/sticky

Should we use approximate numbers that we're calculating on the frontend or use actual usage numbers?

**Comment by rdubrock** [comment]
I'm going to close this for now, we've done some of these things and further updates would probably merit their own issues
