### ISSUE TITLE
Compatability with grafana version 6.4.3 

### ISSUE THREAD

**Issue by AnandDevan** [grafana/synthetic-monitoring-app#178]
The UI for plugin does not load for grafana version 6.4.3

You can test by running a container: 
docker run -p 3000:3000  -e "GF_INSTALL_PLUGINS=grafana-synthetic-monitoring-app"  grafana/grafana:6.4.3 /bin/bash

The following callstack can be seen in the javascript browser console:

```
Uncaught (in promise) TypeError: E.AppPlugin is not a constructor
    at Module.eval (module.ts:10)
    at n (bootstrap:19)
    at eval (bootstrap:83)
    at eval (module.js:2)
    at i (system.js:4)
    at system.js:4
    at system.js:4
    at O (system.js:4)
    at k (system.js:4)
    at system.js:4
```

The UI shows a Loading message: 
![image](https://user-images.githubusercontent.com/2116907/104771367-2ed27500-5740-11eb-9c72-22df34df007e.png)

**Comment by rdubrock** [comment]
The plugin requires v7 or greater, we don't have plans to support earlier versions of Grafana at the moment.
