### ISSUE TITLE
Abstract UI text into a constants file

### ISSUE THREAD

**Issue by rdubrock** [grafana/synthetic-monitoring-app#185]
We have all the UI text scattered around the UI in line with the rest of the code. For better maintainability and future-proofness we should pull that all into constants files. 

Should we have each component keep a constants file, and roll them all up into a single file at the root, or just go with one big file? Other options?

**Comment by Vivek-Prajapatii** [comment]
HI @rdubrock can i pick this up, as im new to this project and can you please guide me up with it?
thank you

**Comment by peterschretlen** [comment]
Closing as unplanned, will pick this up as i18n is added to the roadmap
