### ISSUE TITLE
Label names/values need validation in the check form

### ISSUE THREAD

**Issue by rdubrock** [grafana/synthetic-monitoring-app#215]
Trying to add an invalid label name will result in a cryptic error message. We should validate those fields.

Additionally, the backend is probably returning a more useful error. We should make sure the UI is looking in the right place to find the error.

<img width="591" alt="Screenshot 2021-02-22 at 15 07 35" src="https://user-images.githubusercontent.com/8377044/109186609-92878f00-773d-11eb-8ac2-81fc4bb95f01.png">

**Comment by inf0rmer** [comment]
For context in this case the backend returns:

```json
{
  "err": "invalid label name",
  "msg": "invalid updated check"
}
```

The backend doesn't explain why the label name is invalid, but looking in the [Prometheus documentation](https://prometheus.io/docs/concepts/data_model/) one finds:
> Label names may contain ASCII letters, numbers, as well as underscores. They must match the regex [a-zA-Z_][a-zA-Z0-9_]*. Label names beginning with __ are reserved for internal use.
