### ISSUE TITLE
False alerts 7, 14, 21, and 28 days after gap in stored metrics

### ISSUE THREAD

**Issue by simonc6372** [grafana/synthetic-monitoring-app#231]
Synthetic monitoring uses the following query and triggers an alert on NODATA. 
![image](https://user-images.githubusercontent.com/8004654/110471745-67edec80-80d4-11eb-83e8-a9c0c4301170.png)

However, if there is an outage on day 1, that triggers an alert, there will be another alert triggered on the 7th, 14th, 21st and 28th day anniversary of that outage.

**Comment by rdubrock** [comment]
Is this still the case @mem? I can't find any reference to offsets in our alert rules anymore. Maybe this one should be closed

**Comment by peterschretlen** [comment]
We have modified the expressions to avoid this situation.  Current recording rules do not use offsets:
<img width="1759" alt="image" src="https://github.com/grafana/synthetic-monitoring-app/assets/7903188/147ce23d-45e3-4243-b315-5960fac68854">
