### ISSUE TITLE
Change Font Size and Remove Columns in new Table view?

### ISSUE THREAD

**Issue by ealmonte32** [grafana/synthetic-monitoring-app#242]
Hello,
In the previous synthetic monitoring fields, there was an option to increase font size of text inside the table to 125% or 150%, etc, but on the new Table panel, I cannot find this.
Also on the new Table panel, I don't see a way to remove certain columns from the table, for example I removed the Time and check_name from the Overrides, but they still show up on the panel. I was able to remove these from deprecated panel table.

Thanks.

![image](https://user-images.githubusercontent.com/24350198/112212052-e4172280-8bf2-11eb-85f3-ee2af874b1f4.png)

**Comment by rdubrock** [comment]
The table has changed a bit, so I think this no longer applies
