### ISSUE TITLE
x509 cert signed by unknown authority when HTTP check

### ISSUE THREAD

**Issue by ealmonte32** [grafana/synthetic-monitoring-app#249]
I am wondering if the HTTP check is giving this error because it is trying to connect to target using the IP address instead of the FQDN, if so, why would it be doing that if this is an HTTP check? Meaning, why is it trying to resolve the URL into an IP and doing the HTTP check that way?

The error on log:
![image](https://user-images.githubusercontent.com/24350198/113578143-5410aa00-95f0-11eb-8047-d22f5ec06725.png)

The certificate check on browser:
![image](https://user-images.githubusercontent.com/24350198/113577971-1ca1fd80-95f0-11eb-94c7-a47ad8f88f00.png)

**Comment by rdubrock** [comment]
Hiya @ealmonte32, that was a choice made by [prometheus blackbox exporter](https://github.com/prometheus/blackbox_exporter/), which is the core of the [synthetic monitoring agent](https://github.com/grafana/synthetic-monitoring-agent). You can see the much of the discussion in [this issue](https://github.com/prometheus/blackbox_exporter/issues/264)

**Comment by ealmonte32** [comment]
@rdubrock Thanks for that link.. I guess unless I compile my own exporter I just have to deal with that error/alert.
