### ISSUE TITLE
Pages are stuck with loading screen when API is unavailable 

### ISSUE THREAD

**Issue by electron0zero** [grafana/synthetic-monitoring-app#273]
**What happened**:
All plugin pages were stuck on loading screen

See attached gif:
![sm_loading_when_api_down](https://user-images.githubusercontent.com/9503187/119814130-b064bb80-bf07-11eb-8baa-6c0080c37775.gif)

**What you expected to happen**:
Plugin page should load and report an error that API is unavailable

**How to reproduce it (as minimally and precisely as possible)**:
- Install Plugin
- Use custom apiHost in provisioning file
- Take down API
- Load any page and it will be stuck on loading screen

**Anything else we need to know?**:

**Environment**:
- Grafana version (if running on prem): Grafana v7.5.7 (91de51771c)
- SM plugin version: 0.11.0
- OS Grafana is installed on: Grafana Cloud Hosted Grafana
- User OS & Browser: Firefox on Ubuntu Linux
- Others:

**Comment by electron0zero** [comment]
@rdubrock noticed same bug (all plugin pages are stuck on loading) when SM API returns `403 Forbidden`

**details:**
endpoint: `/api/datasources/proxy/13/sm/tenant`
response: `{"msg":"invalid API authorization token","err":"invalid API token"}`

![image](https://user-images.githubusercontent.com/9503187/122581760-047d3e80-d075-11eb-8543-66a919062e50.png)

![image](https://user-images.githubusercontent.com/9503187/122581918-31315600-d075-11eb-8c46-6417ba41d93b.png)

**Comment by jewbetcha** [comment]
Fixed with https://github.com/grafana/synthetic-monitoring-app/pull/405
