### ISSUE TITLE
Rename to Synthetic monitoring

### ISSUE THREAD

**Issue by woodsaj** [grafana/synthetic-monitoring-app#32]
we have decided to re-brand worldping as "Synthetic Monitoring".  This is more inline with existing solutions in the market and is aligned with this no-ops monitoring capability being part of Grafana Cloud, rather then a standalone product.

**Comment by mem** [comment]
This means changing all the user-visible strings.

Do we change the name of the programs, too? Log entries? The worldping_check_info metric?

**Comment by woodsaj** [comment]
@mem given that we have not launched the product, it would probably make sense to change everything.
