### ISSUE TITLE
Add a negative filter for checks

### ISSUE THREAD

**Issue by electron0zero** [grafana/synthetic-monitoring-app#351]
**What would you like to be added**:
We have ways to filter by check type, status, and labels but there is no way to have to do a negative filter.

**Why is this needed**:

as of today, we can't filter and answer following questions:
- show me all the checks that doesn't have a label (e.g: team label) 
- show me all the checks that are not running on a probe (e,g. Ohio)
	- e.g: I added a new private probe and want to see which checks are not running on it
- show me all the checks that doesn't have prod label
- show me all the checks that are not of type HTTP

**Additional details**

Why should we add negative filter?

I added private probe, and had to go to each checks add that private probe. 

It's hard to see if I already added that probe to a check without going to the check, and checking it. I had to keep track of checks that I updated to use my recently added private probe.

Would have been nice to filter probe!="my_new_private_probe" and see the checks that are not using that probe.

---
related to #350

**Comment by jewbetcha** [comment]
I'm not sure about this one... We seem to be at a critical mass of filters on the list of checks, and adding another one would make the UI pretty intense. If we were to add a negative filter of some sort, we might want to re-think the filters in general under some unified input.

**Comment by electron0zero** [comment]
makes sense, I will go ahead and close this.
