### ISSUE TITLE
Multiple targets per check type

### ISSUE THREAD

**Issue by danielschaerli** [grafana/synthetic-monitoring-app#359]
**What would you like to be added**:
In Synthetic Monitoring each check has to have one fixed target. So I have to create a check of the same type for each target:
check_ping(foo.com)
check_ping(bar.com)
check_http(foo.com)
check_http(bar.com)

It would be useful to be able to group several targets and assign the check to this group.
container = ['foo.com', 'bar.com']
check_ping(container)
check_http(container)

**Why is this needed**:
- Reduce the number of checks of the same type.
- Better overview

**Additional context**:

**Comment by electron0zero** [comment]
Hi 👋🏼, wanted to share that we have terraform support and API to manage checks programmatically, [see docs](https://grafana.com/docs/grafana-cloud/synthetic-monitoring/#config-as-code).

**Comment by rdubrock** [comment]
I think through the newly released scripted checks based on k6, as well as MultiHTTP, this functionality can be achieved. I don't think there are any plans to make the more basic protocol checks multidimensional, but I think scripting is flexible enough to get this job done.
