### ISSUE TITLE
Unable to create a new check after Frequency or Timeout value was deleted and re-added

### ISSUE THREAD

**Issue by besartberisha** [grafana/synthetic-monitoring-app#378]
**What happened**:
As I was adding a new check, I accidentally deleted the frequency value, and then when I added it again, the error message wasn't being updated, so I wasn't able to submit the form.

**What you expected to happen**:
Adding a new check

**How to reproduce it (as minimally and precisely as possible)**:
Start by adding a new check, in the `Frequency` input make sure to delete the `60` number, you'll see a `Frequency must be at least 10 seconds` error which even after it gets updated the error won't go away, the same case is with the `Timeout` field as well.

**Anything else we need to know?**:

https://user-images.githubusercontent.com/7255779/141149539-c4c5b9ad-62de-46a5-bdc1-953301c23a76.mov

**Environment**:
- Grafana version (if running on prem): v8.2.3-40566 (3b8be57b4f)
- SM plugin version: 1.5.5
- User OS & Browser: MacOS Big Sur, Firefox:  94.0.1

**Comment by rdubrock** [comment]
Thanks for the detailed repro steps @besartberisha!

**Comment by jewbetcha** [comment]
Fix for this is going out today!

**Comment by justinTM** [comment]
This is still an issue in version v8.3.4 (a551d74b1)

<img width="406" alt="image" src="https://user-images.githubusercontent.com/9123665/150606336-57265023-29fd-4320-819d-9b94253c6243.png">

steps to reproduce:
1. type in "300" for frequency seconds
2. move slider anywhere between "10" and "120"
3. click "Save"
4. get error above

**Comment by jewbetcha** [comment]
@justinTM which version of Synthetic Monitoring do you have installed?

**Comment by justinTM** [comment]
not sure how to check. whatever version comes with Grafana Cloud version v8.3.4 (a551d74b1)

**Comment by jewbetcha** [comment]
If you hover over the Synthetic Monitoring icon on the left sidebar, and go to "Config", you will see the version at the top there

<img width="894" alt="Screen Shot 2022-01-24 at 8 12 21 AM" src="https://user-images.githubusercontent.com/7724615/150798560-a22d3c6b-caa4-4624-89af-eb0d4645eca6.png">
