### ISSUE TITLE
Error deleting a private probe

### ISSUE THREAD

**Issue by brittenhouse** [grafana/synthetic-monitoring-app#39]
Steps to reproduce:
1. Create a private probe;  SM->Probes, click "New"
2. Delete the probe; SM->Probes, select probe, click "Delete Probe"

No on-screen error is displayed, but an error is received from the network request:
```
{ "msg":"failed to delete probe 23 from database",
  "err":"deleting probe: Error 1054: Unknown column '$1' in 'where clause'"}
```

The same error is received whether a probe was ever online or not.

**Comment by woodsaj** [comment]
This is a bug in the backend api.  i have opened an issue there.
