### ISSUE TITLE
Dashboards should handle data gaps more gracefully

### ISSUE THREAD

**Issue by rdubrock** [grafana/synthetic-monitoring-app#394]
Currently if there is a gap in the data, the success rate panes will show `NaN`. We have a couple options:

1.) Try and ignore the gap, and default to 100% success rate
2.) Try and ignore the gap, and default to 0% success rate
3.) Not ignore the gap and show NaN
4.) Not ignore the gap but show something nicer than NaN, like `No Data` or `Data Missing`

**Comment by rdubrock** [comment]
Number 4 is probably the best route forward

**Comment by electron0zero** [comment]
Yup, I think 4) makes sense.

**Comment by jewbetcha** [comment]
x2 #4

**Comment by rdubrock** [comment]
I can't reproduce this anymore, I think through the many iterations of the dashboards this got fixed at some point
