### ISSUE TITLE
Remove the OR clauses in the dashboards

### ISSUE THREAD

**Issue by rdubrock** [grafana/synthetic-monitoring-app#401]
In order to navigate a metric name change (from `probe_success` to `probe_all_success`), we added an `OR` clause to many of the queries in our dashboards. I think that the time window of needing to worry about that metric naming has passed, so we could maybe get rid of all those OR clauses now.

**Comment by electron0zero** [comment]
https://github.com/grafana/synthetic-monitoring-app/pull/114 was merged 1 year and 5 months ago.

we can now remove old metrics from plugin code, alerts and dashboards.
