### ISSUE TITLE
Summary dashboard uptime column is showing more than 100%

### ISSUE THREAD

**Issue by rdubrock** [grafana/synthetic-monitoring-app#457]
![Screen Shot 2022-04-13 at 11 36 28](https://user-images.githubusercontent.com/8377044/163256784-cfcdb59f-a2a4-4721-90f1-71fd0908435c.png)

Something is sideways with the uptime query in the summary dashboard

**Comment by electron0zero** [comment]
#446 should have fixed this, can you check if we can reproduce this issue with #446  merged?

**Comment by ernestmak** [comment]
Is there any update on this issue?

**Comment by skeilson** [comment]
We appear to have another report of this described problem - [ZD ticket #53899](https://grafana.zendesk.com/agent/tickets/53899) - opening a support-escalation for continuity and visbility.
