### ISSUE TITLE
Increase HTTP check url limit beyond the current 64 characters

### ISSUE THREAD

**Issue by brittenhouse** [grafana/synthetic-monitoring-app#47]
Target validation check:
https://github.com/grafana/synthetic-monitoring-app/blob/c39fcfb674f7fd91d977dc1cdaa1303aa4196f01/src/validation.ts#L32-L35

**Comment by mem** [comment]
API accepts longer targets, so we only need to agree on a number.

**Comment by woodsaj** [comment]
the target is used as the "instance" label.  Cortex/Loki allow up to 2048 (which happens to be the maximum allowed URL length).
However, having such long label values is not great for UX, but we still could allow it.

The alternative is to allow query params to be passed via a separate field.  So the target field will continue to be used as the "instance" label, but when executing the check we pass the target to BBE as target+query.  We already do this with the cacheBustingQueryParamName.

**Comment by electron0zero** [comment]
> allow query params to be passed via a separate field.

I think keeping it in separate field make sense

>  We already do this with the cacheBustingQueryParamName.

doing the same here will mean we are consistent across the board

but one can make a valid case that taking full URL(with params) as single input is better from UX standpoint. (see here how postman takes full URL and autofills query params)
[
![url_in_postman](https://user-images.githubusercontent.com/9503187/88214097-3e806d80-cc77-11ea-800e-d2f79bdff013.gif)
](url)

**Comment by woodsaj** [comment]
good point @electron0zero 
users are likely going to be simply pasting in the URL from somewhere.  If there are query params, perhaps the app could show a modal that asks the user if they want the params moved to the separate "params" field.

**Comment by eamonryan** [comment]
Rather than ask, interrupting the flow and requiring a response, maybe just shift them automatically like in the gif above and have an informational "We moved these for you just FYI" dialog?
