### ISSUE TITLE
DNS Validation fails because expression is saved inverse

### ISSUE THREAD

**Issue by CSalih** [grafana/synthetic-monitoring-app#475]
**What happened**:
If I add in a DNS Check a `Validate Answer matches` Validation with `x\.x\.x\.x` (this is the A Record of the target) as expression and without checking "Invert Match" then this check will fail but doing this with a checked "Invert Match" will pass. Idk if this is a bug or did I not understand the validation rule behavior?

**Request Body if i hit "Save" without selecting "Invert Match"**
```
# /api/datasources/proxy/11/sm/check/update
...
"validateAnswerRRS": {
  "failIfMatchesRegexp": [
    "x\.x\.x\.x"
  ],
  "failIfNotMatchesRegexp": []
}
```

**What you expected to happen**:
Check should pass without checking "Invert Match".

**How to reproduce it (as minimally and precisely as possible)**:
I will use google as domain but you can replace that with any domain
1. Add a DNS Check with target: "google.com"
2. Set any probe location. I used Paris
3. Under Validation click on `Add regex Validation` and add following
  * DNS Response Match: Validate Answer matches
  * Expression: 142\.250\.184\.46
  * Invert Match: Not selected

**Anything else we need to know?**:
If you add `Validate Additional matches` with any Expression and hit save then this save will be discarded but it seems like a bug on the backend (if i take a look at the request/response) but i will create another ticket for this. 

**Environment**:
- Grafana version (if running on prem): 9.0.5 (Grafana Cloud)
- SM plugin version: 1.9.20
- OS Grafana is installed on: Grafana Cloud

**Comment by pabstma** [comment]
+1 for fixing this.

I ran into this issue too, wondering why the validation failed.
