### ISSUE TITLE
Disallow body regex validation on HTTP HEAD checks

### ISSUE THREAD

**Issue by adriansr** [grafana/synthetic-monitoring-app#483]
HTTP checks using the HEAD method should not allow setting Regex Validations on body, as there is no body in HEAD requests.

**Comment by CatPerry** [comment]
@adriansr Assuming you want frontend to disallow this, and it's not some backend fix that you're thinking up? If so, I can fix this.

**Comment by adriansr** [comment]
Yes @CatPerry , I meant the UI should disallow setting Regex Validations on an HTTP request body when HEAD method is selected.
