### ISSUE TITLE
Extend the timeout from max 10 sec to 30 sec

### ISSUE THREAD

**Issue by yoramshai** [grafana/synthetic-monitoring-app#519]
**What would you like to be added**:
Currently, the max timeout for a check is 10-sec max which results in HTTP response status equal to 0 and a latency of 10sec. It would be great if you could extend it to 30sec like in other checks platforms.

  **Why is this needed**:
When it happens, it hides the numbers we are looking for with the high latency. 
In the end, it is not only to measure up/down but also to make latency improvements, which is challenging at this moment.  
Note that when it happened, the latency was around ±11-15 sec.
In addition, it influences the reachability percentage, as the timeout counts as "down" even if the request is completed after 12 seconds.

**Additional context**
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/11707803/217471617-a0a24ad7-fcb3-4f79-a093-0b409947affa.png">

**Comment by peterschretlen** [comment]
This is addressed in https://github.com/grafana/synthetic-monitoring-app/pull/731
<img width="666" alt="image" src="https://github.com/grafana/synthetic-monitoring-app/assets/7903188/1101b2c3-effd-4358-baab-531efc144107">

**Comment by yoramshai** [comment]
Thank you so much !
