### ISSUE TITLE
On prem config

### ISSUE THREAD

**Issue by suikast42** [grafana/synthetic-monitoring-app#546]
As I unerstand, this plugin requiers a grafana cloud instance of grafana. 

It possible or planed ( if not possible ) to use this plugin with a on premise solution wihtout a grafana cloud account ?

**Comment by rdubrock** [comment]
Howdy @suikast42, it isn't possible at the moment, and we currently don't have any plans to do the work required to get all the backend systems into a place where they could be open sourced. Sorry, I know that's not the most fun answer. You can make a fair few checks for free in grafana cloud, though, so hopefully that's some consolation!
