### ISSUE TITLE
Usage of single quote in a check job or instance causes dashboard to show no data

### ISSUE THREAD

**Issue by ka3de** [grafana/synthetic-monitoring-app#676]
**What happened**:
An check created with a `job` name or `instance` value that contains a single quote `'` makes the dashboard panels to show `No Data` even if the check is actually running and the data is available. Notice that exploring the panel queries seems to work OK, and the queries themselves are shown correctly.

**What you expected to happen**:
The dashboard panels show the check data.

**How to reproduce it (as minimally and precisely as possible)**:
Create an HTTP check with values:
- job: `Test single quotes`
- instance: `https://grafana.com/'test'`
Or:
- job: `Test single 'quotes'`
- instance: `https://grafana.com`

![Screenshot from 2024-02-07 16-25-52](https://github.com/grafana/synthetic-monitoring-app/assets/6529572/d96af0d5-691b-4132-a9fa-4839c39c2ef1)

**Anything else we need to know?**:

**Environment**:
- SM plugin version: 1.12.5
- OS Grafana is installed on:
- User OS & Browser: Linux Ubuntu, Firefox 122.0
- Others:

**Comment by rdubrock** [comment]
See also https://github.com/grafana/synthetic-monitoring-app/issues/610

This is, I think, because of how Grafana itself escapes dashboard variable values, not necessarily connected to synthetics itself

**Comment by ka3de** [comment]
> See also https://github.com/grafana/synthetic-monitoring-app/issues/610
> This is, I think, because of how Grafana itself escapes dashboard variable values, not necessarily connected to synthetics itself

Ah, I did search for issues with `quote` or `'` in the issue name but found nothing, missed `apostrophes`. I guess we can close this one as duplicate an prioritize the other one if there's something we can do.
