### ISSUE TITLE
private probes do not send tracks and has no reachability

### ISSUE THREAD

**Issue by shypkov** [grafana/synthetic-monitoring-app#681]
**What would you like to be added**:

is it connected to logged error?
[core] [pick-first-lb 0xc000161b30] Received SubConn state update: 0xc000161cb0, {ConnectivityState:CONNECTING ConnectionError:<nil>}"}

**Why is this needed**:
![image](https://github.com/grafana/synthetic-monitoring-app/assets/90761209/0334226d-76b1-4ed2-a0a7-d88cca4699b2)

**Additional context**

**Comment by shypkov** [comment]
the main error i receive is
[core] [pick-first-lb 0xc000161b30] Received SubConn state update: 0xc000161cb0, {ConnectivityState:CONNECTING ConnectionError:}"}

**Comment by peterschretlen** [comment]
I suspect this is related to the private probe issue reported in #682  . As this is not an enhancement request, I am going to close the issue. 

For questions and troubleshooting like this, I would recommend posting in the community forum under the `synthetic-monitoring` tag:  https://community.grafana.com/tag/synthetic-monitoring
