### ISSUE TITLE
Redesign the initialization page

### ISSUE THREAD

**Issue by rdubrock** [grafana/synthetic-monitoring-app#743]
It currently has outdated screenshots and needs to be simpler with a clearer call to action. Context is here: https://raintank-corp.slack.com/archives/C06QZTTA7AT/p1712116834826599

**Comment by majavojnoska** [comment]
Hey everyone. Here are two versions of the Synthetics landing page, with and without the "Get started now" section. 
* v1 Baseline design | [Figma](https://www.figma.com/file/WXbmUSpCMlJHG8fpjvmGT1/Synthetics-(DevReady)?type=design&node-id=2045-27767&mode=design&t=4HAh3RtmOeJvbSLS-4) | [Prototype](https://www.figma.com/proto/WXbmUSpCMlJHG8fpjvmGT1/Synthetics-(DevReady)?page-id=2032%3A21644&type=design&node-id=2045-27767&viewport=848%2C19%2C0.25&t=7rkeb81rfjxPtheu-9&scaling=min-zoom&starting-point-node-id=2045%3A27767&show-proto-sidebar=1)
* v2 with “Get started now”| [Figma](https://www.figma.com/file/WXbmUSpCMlJHG8fpjvmGT1/Synthetics-(DevReady)?type=design&node-id=2062-15127&mode=design&t=4HAh3RtmOeJvbSLS-4) | [Prototype](https://www.figma.com/proto/WXbmUSpCMlJHG8fpjvmGT1/Synthetics-(DevReady)?page-id=2032%3A21644&type=design&node-id=2062-15127&viewport=848%2C19%2C0.25&t=7rkeb81rfjxPtheu-9&scaling=min-zoom&starting-point-node-id=2062%3A15127&show-proto-sidebar=1)

<img width="1440" alt="01 Synthetics _ Landing page" src="https://github.com/grafana/synthetic-monitoring-app/assets/17724531/366cca3d-3a8f-4938-a287-92987e0eb08e">
<img width="1440" alt="01_2 Synthetics _ Landing page - Scripting with k6" src="https://github.com/grafana/synthetic-monitoring-app/assets/17724531/70397723-6b30-4ea7-8751-5c78b3caf2f4">
<img width="1440" alt="01_3 Synthetics _ Landing page - Scripting with k6-1" src="https://github.com/grafana/synthetic-monitoring-app/assets/17724531/143ba6cd-c1c1-4ffe-8626-506b794849dc">
<img width="1440" alt="01_4 Synthetics _ Landing page - Scripting with k6-2" src="https://github.com/grafana/synthetic-monitoring-app/assets/17724531/7eac1563-953d-4f71-94f0-afa88cf4e57d">


<img width="1440" alt="02 Synthetics _ Landing page v2" src="https://github.com/grafana/synthetic-monitoring-app/assets/17724531/800a5725-c3af-4bb3-bd1f-862cba490f7b">
