### ISSUE TITLE
Convert checks page to utilize URL parameters

### ISSUE THREAD

**Issue by ckbedwell** [grafana/synthetic-monitoring-app#762]
**What would you like to be added**:
Currently the checks page utilizes localStorage as a way to replicate state. This is problematic for a number of reasons and should be removed. It should be updated by utilizing URL query parameters instead. 

**Why is this needed**:
The localStorage state can be a huge hinderance and unwanted behaviour in certain user workflows. Changing the state to url query parameters means we can persist check page state when navigating the app via back and forward buttons, and it also enables the ability to deep-link and share the checks list page from other applications as well as in peer-to-peer sharing.

Please ensure the solution is easily extensible as we add more filters in the future.

**Additional context**
[Product board link.](https://grafana.productboard.com/entity-detail/features/26915022)

**Comment by rdubrock** [comment]
Fixing this would close #607
