### ISSUE TITLE
During setup it's not clear that you MUST select instances

### ISSUE THREAD

**Issue by mem** [grafana/synthetic-monitoring-app#83]
During setup, the common case will be that the user will have one hosted metrics and one hosted logs instance.

When the user gets to the instance selection screen, they see this:

![instance-selection](https://user-images.githubusercontent.com/189701/91743038-703cfc00-eb74-11ea-8a26-aa78438e6234.png)

simply pressing setup produces an error (good!) but it's not clear that the problem is that instances have not been selected: a pop up message from the browser says "Missing metrics instance".

**Comment by mem** [comment]
From my point of view, for the usual case of only one HM / HL instance, I think it's appropriate to preselect the only instances that are available. In the case of users that do have more than one instance, we could either pick the "first" by default (ordering by ID or name to define "first") so that it's move evident that something is selected, or we could leave it as it is today. Maybe with a different widget it would be more obvious that something is selected or that a selection has to be made?

**Comment by rdubrock** [comment]
I think default selecting if there is only one option is a great idea, but personally I think if there is more than one we should make the user select before proceeding. It can be easy to get on autopilot when clicking through config screens. The `Setup` button should probably be disabled if the user hasn't selected instances
