### ISSUE TITLE
Provide a visual clue as to where a probe is located?

### ISSUE THREAD

**Issue by mem** [grafana/synthetic-monitoring-app#84]
When creating a probe, this is what you see:

![new-probe](https://user-images.githubusercontent.com/189701/91743985-fb6ac180-eb75-11ea-8533-45ac3c1ebb17.png)

it would be nice to have some visual feedback as to what those numbers correspond to.

**Comment by mem** [comment]
We already have the worldmap panel available and I wonder if it's possible to use it for this: simply show the location as the user is entering it.

I imagine this would save some users the uncertainty of whether they got lat / long right or flipped. It would also help with what's positive and what's negative.

**Comment by mem** [comment]
@rdubrock any take on this?

**Comment by jewbetcha** [comment]
Released with 1.9.7
