### ISSUE TITLE
`query` API is missing from synthetic monitoring

### ISSUE THREAD

**Issue by peterschretlen** [grafana/synthetic-monitoring-app#867]
**What happened**:

The [client API](https://github.com/grafana/synthetic-monitoring-api-go-client/blob/main/docs/API.md#apiv1checkqueryjobjobtargettarget) docs mention this API: 
```
GET /api/v1/check/query?job=:job:&target=:target:
```

But calling that API gives back a `400` with message: 
```
{"msg":"invalid check ID accessing /api/v1/check/query","err":"invalid id \"query\""}
```

**How to reproduce it (as minimally and precisely as possible)**:

- get an API token from the config page
- call `curl -H "Authorization: Bearer <your-token-here>" https://<synthetics-backend-address-from-config-page>/api/v1/check/query`

**Comment by d0ugal** [comment]
The handler was removed here; https://github.com/grafana/synthetic-monitoring-api/commit/c85ed8ca0f7715cdf2ba3c3577fdb4a0661e31ad#diff-67daa38c612c4e37cdf6c61241ba2128dbf193398522071be4be5c7d7acbf256L87

It looks like the removal was accidental as there is no mention of it in the discussion. 8 `/v1/check/*` endpoints were deleted and 7 added.

![Image](https://github.com/user-attachments/assets/c5f1d887-06c6-422a-a1ea-df80054263c4)
