### ISSUE TITLE
Warn you are leaving check edit page when unsaved data is present

### ISSUE THREAD

**Issue by ckbedwell** [grafana/synthetic-monitoring-app#892]
## Problem

When creating or editing a check you can spend a long time filling out all the fields, only to accidentally click a link, back/forward button etc. and immediately lose all of your work.

## Completion criteria

A confirmation that you want to leave the page without saving your work when you have 'dirty' form fields on the check creation page should be presented to the user.

Please ensure the appropriate integration tests have been added when submitting the PR.

**Comment by majavojnoska** [comment]
I also think that implementing a confirmation dialog when users attempt to leave the page with unsaved changes is a great solution to prevent accidental data loss. The dialog should:
    * Clearly explain the situation: "You have unsaved changes. Are you sure you want to leave this page?"
    * Offer clear actions: "Stay on Page" and "Leave Page" buttons.
